### ISSUE TITLE
Copy the link to a specific project

### ISSUE THREAD

**Issue by Hendercraft** [AgileFrontend/AgileFrontend#22]

**Comment by Hendercraft** [comment]
Copy the link to a specific post :
Make the post appear
-Check the service / back so it appear under /posts:idsmthg

**Comment by samaritan-mt** [comment]
done with the share button in #60 
each post with a postID in the database is now accessible through the route post?id=firebase_ref

**Comment by samaritan-mt** [comment]
Yeah just verified on the latest PR link it's working for every post using it's ref I'll let you close the issue if you want ;)
