### ISSUE TITLE
Make the like button work

### ISSUE THREAD

**Issue by Hendercraft** [AgileFrontend/AgileFrontend#63]

**Comment by Hendercraft** [comment]
Make the like button display the current amount of like
Store the uid in as likes to a post in order to prevent multiple likes
The number of like is the size of the array

**Comment by Hendercraft** [comment]
Don't forget to add the function to remove likes too

**Comment by samaritan-mt** [comment]
I was thinking of a map to associate a userID with liked posts ID's as a base object for the likes. The number of likes is the length of values and it provides us with a way to retrieve the likes of each user and of course a userID has unique values. what do you think @Hendercraft ?

**Comment by samaritan-mt** [comment]
see #74 PR implemented pending review and merge can be considered done
