### ISSUE TITLE
Fix liked projects not displaying when the user reloads the page

### ISSUE THREAD

**Issue by BenjaminCDP** [AgileFrontend/AgileFrontend#77]
Probably solved by checking if the current user has his ID that match with the array of UserID included in the project

**Comment by samaritan-mt** [comment]
I'll check this out

**Comment by samaritan-mt** [comment]
Are you talking about the color or the number of likes ? @BenjaminCDP

**Comment by Hendercraft** [comment]
The color

**Comment by samaritan-mt** [comment]
I'm on it

**Comment by samaritan-mt** [comment]
see #82  (I love circular recursivity) fixed
