### ISSUE TITLE
Fix ghost post message in user profile

### ISSUE THREAD

**Issue by Hendercraft** [AgileFrontend/AgileFrontend#80]
It seems like we still see a link to post that don't exist anymore in the user profile page

**Comment by Hendercraft** [comment]
![image](https://github.com/AgileFrontend/AgileFrontend/assets/50171749/9deafe70-bb76-4936-9692-1d9f66df306a)
got this console error :
ERROR TypeError: this.post is undefined
profile image is not displayed
Might be related to the fact that the data is read from on init, might need to be changed to Onchange ?

**Comment by samaritan-mt** [comment]
stupid mistake here i removed an else statement from the post fetcher function so it's fixed in the likes bug branch @Hendercraft

**Comment by samaritan-mt** [comment]
See #82 fixed
